package dev.clientify.client.hud;

import com.mojang.blaze3d.platform.NativeImage;
import com.mojang.blaze3d.systems.RenderSystem;
import dev.clientify.client.ClientifyClient;
import java.util.function.IntUnaryOperator;
import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.Font;
import net.minecraft.client.gui.GuiGraphicsExtractor;
import net.minecraft.client.renderer.RenderPipelines;
import net.minecraft.client.renderer.texture.DynamicTexture;
import net.minecraft.resources.Identifier;

/**
 * A small caps alphabet: every letter is a capital, five pixels tall, sitting on the vanilla
 * baseline. Digits, punctuation and anything else stay the game's own glyphs at full height, which
 * is what makes it read as small caps rather than as small text.
 *
 * <p>The letters are drawn here as pixels rather than by shrinking Minecraft's font. Scaling a
 * bitmap font by three quarters lands its rows between pixels and the result is mush — that was
 * the first attempt at this and it looked exactly as bad as it sounds. Purpose-drawn glyphs at the
 * size they are shown stay sharp.
 *
 * <p>Not the resource pack the idea came from: that one is All Rights Reserved, so its art cannot
 * ship here. Anyone who installs it gets the same look through the plain Minecraft font option,
 * since that draws with whatever font the game has loaded.
 */
public final class SmallCaps {
	/** Glyph height. Vanilla capitals are seven, so these sit two pixels lower on the baseline. */
	private static final int H = 5;
	private static final int BASELINE_DROP = 2;
	private static final int CELL = 6;
	private static final int COLS = 8;
	private static final int ROWS = 5; // 26 letters + 10 digits

	private static final Identifier ATLAS = ClientifyClient.id("smallcaps");

	/**
	 * Five rows per glyph, '#' where a pixel goes; the advance adds one column.
	 *
	 * <p>Generated by {@code tools/SmallCapsGen.java} from Minecraft's own ascii.png — each
	 * capital trimmed to its ink and squeezed to five rows by dropping whichever rows merely
	 * repeat the one above. That keeps the game's shapes; letters drawn from scratch did not look
	 * like the font they sit next to, which was the complaint. A handful (H, K, N, 4, 7, 9) are
	 * corrected by hand where the automatic squeeze moved a crossbar off centre.
	 */
	private static final String[][] ALPHABET = {
			{"A", ".###.", "#...#", "#####", "#...#", "#...#"},
			{"B", "####.", "#...#", "####.", "#...#", "####."},
			{"C", ".###.", "#...#", "#....", "#...#", ".###."},
			{"D", "####.", "#...#", "#...#", "#...#", "####."},
			{"E", "#####", "#....", "###..", "#....", "#####"},
			{"F", "#####", "#....", "###..", "#....", "#...."},
			{"G", ".####", "#....", "#..##", "#...#", ".###."},
			{"H", "#...#", "#...#", "#####", "#...#", "#...#"},
			{"I", "###", ".#.", ".#.", ".#.", "###"},
			{"J", "....#", "....#", "....#", "#...#", ".###."},
			{"K", "#...#", "#..#.", "###..", "#..#.", "#...#"},
			{"L", "#....", "#....", "#....", "#....", "#####"},
			{"M", "#...#", "##.##", "#.#.#", "#...#", "#...#"},
			{"N", "#...#", "##..#", "#.#.#", "#..##", "#...#"},
			{"O", ".###.", "#...#", "#...#", "#...#", ".###."},
			{"P", "####.", "#...#", "####.", "#....", "#...."},
			{"Q", ".###.", "#...#", "#...#", "#..#.", ".##.#"},
			{"R", "####.", "#...#", "####.", "#...#", "#...#"},
			// S and 5 widen their bottom bar instead of copying the font's. Both lose the "#...#"
			// row that walls the lower bowl, and without it a three pixel bar hangs off the right
			// and the tail reads short. Four pixels balances the top bar, which is what the eye
			// compares it against.
			{"S", ".####", "#....", ".###.", "....#", "####."},
			{"T", "#####", "..#..", "..#..", "..#..", "..#.."},
			{"U", "#...#", "#...#", "#...#", "#...#", ".###."},
			{"V", "#...#", "#...#", ".#.#.", ".#.#.", "..#.."},
			{"W", "#...#", "#...#", "#.#.#", "##.##", "#...#"},
			{"X", "#...#", ".#.#.", "..#..", ".#.#.", "#...#"},
			{"Y", "#...#", ".#.#.", "..#..", "..#..", "..#.."},
			{"Z", "#####", "...#.", "..#..", ".#...", "#####"},
			{"0", ".###.", "#...#", "#.#.#", "#...#", ".###."},
			{"1", "..#..", ".##..", "..#..", "..#..", "#####"},
			{"2", ".###.", "#...#", "..##.", ".#...", "#####"},
			{"3", ".###.", "#...#", "..##.", "....#", ".###."},
			{"4", "...##", ".#..#", "#####", "....#", "....#"},
			{"5", "#####", "#....", "####.", "....#", "####."},
			{"6", "..##.", ".#...", "####.", "#...#", ".###."},
			{"7", "#####", "....#", "...#.", "..#..", "..#.."},
			{"8", ".###.", "#...#", ".###.", "#...#", ".###."},
			{"9", ".###.", "#...#", ".####", "....#", ".##.."},
	};

	private static final int[] WIDTH = new int[ALPHABET.length];
	private static boolean ready;
	private static boolean failed;

	private SmallCaps() {
	}

	/** Cell for a character, or -1 for anything the sheet does not cover. */
	private static int index(char c) {
		char upper = Character.toUpperCase(c);
		if (upper >= 'A' && upper <= 'Z') {
			return upper - 'A';
		}
		// Digits shrink with the letters; a line of full-height numbers among small caps looks
		// like two fonts fighting.
		if (upper >= '0' && upper <= '9') {
			return 26 + (upper - '0');
		}
		return -1;
	}

	/** Builds the glyph sheet once the GPU is up; false means fall back to the vanilla font. */
	private static boolean ensure() {
		if (ready) {
			return true;
		}
		if (failed) {
			return false;
		}
		Minecraft mc = Minecraft.getInstance();
		if (mc == null || RenderSystem.getDevice() == null) {
			return false;
		}
		try {
			NativeImage img = new NativeImage(COLS * CELL, ROWS * CELL, true);
			for (int i = 0; i < ALPHABET.length; i++) {
				String[] glyph = ALPHABET[i];
				int cellX = (i % COLS) * CELL;
				int cellY = (i / COLS) * CELL;
				WIDTH[i] = glyph[1].length();
				for (int row = 0; row < H; row++) {
					String bits = glyph[row + 1];
					for (int col = 0; col < bits.length(); col++) {
						if (bits.charAt(col) == '#') {
							img.setPixel(cellX + col, cellY + row, 0xFFFFFFFF);
						}
					}
				}
			}
			mc.getTextureManager().register(ATLAS, new DynamicTexture(() -> "Clientify small caps", img));
			ready = true;
		} catch (Throwable t) {
			ClientifyClient.LOGGER.warn("Small caps glyphs unavailable; using the plain font", t);
			failed = true;
		}
		return ready;
	}

	/** Advance for one character in font units. */
	private static int advance(Font font, char c) {
		int letter = index(c);
		if (letter < 0 || !ready) {
			return font.width(String.valueOf(c));
		}
		return WIDTH[letter] + 1;
	}

	public static float width(Font font, String text) {
		if (!ensure()) {
			return font.width(text);
		}
		float w = 0;
		for (int i = 0; i < text.length(); i++) {
			w += advance(font, text.charAt(i));
		}
		return w;
	}

	/**
	 * Draws {@code text} at (x,y) in font units, colouring character {@code i} by
	 * {@code colorByIndex}.
	 *
	 * <p>Shadows are one pass over the whole run before the letters, as vanilla does it — drawing
	 * each glyph's shadow just before the next glyph lays it over the neighbouring letter.
	 */
	public static void draw(GuiGraphicsExtractor g, Font font, String text, float x, float y,
			IntUnaryOperator colorByIndex, boolean shadow) {
		if (text.isEmpty()) {
			return;
		}
		if (!ensure()) {
			// No sheet yet: plain glyphs keep the text readable rather than dropping it.
			int lx = Math.round(x);
			for (int i = 0; i < text.length(); i++) {
				String ch = String.valueOf(text.charAt(i));
				g.text(font, ch, lx, Math.round(y), colorByIndex.applyAsInt(i), shadow);
				lx += font.width(ch);
			}
			return;
		}
		if (shadow) {
			pass(g, font, text, x + 1, y + 1, i -> shadowOf(colorByIndex.applyAsInt(i)));
		}
		pass(g, font, text, x, y, colorByIndex);
	}

	private static void pass(GuiGraphicsExtractor g, Font font, String text, float x, float y,
			IntUnaryOperator colorByIndex) {
		int cx = Math.round(x);
		int top = Math.round(y);
		for (int i = 0; i < text.length(); i++) {
			char c = text.charAt(i);
			int color = colorByIndex.applyAsInt(i);
			int letter = index(c);
			if (letter < 0) {
				String ch = String.valueOf(c);
				g.text(font, ch, cx, top, color, false);
				cx += font.width(ch);
				continue;
			}
			int u = (letter % COLS) * CELL;
			int v = (letter / COLS) * CELL;
			int w = WIDTH[letter];
			g.blit(RenderPipelines.GUI_TEXTURED, ATLAS, cx, top + BASELINE_DROP, u, v, w, H,
					w, H, COLS * CELL, ROWS * CELL, color);
			cx += w + 1;
		}
	}

	/** Vanilla's own shadow colour: a quarter of the brightness, same alpha. */
	private static int shadowOf(int argb) {
		return (argb & 0xFF000000) | ((argb & 0xFCFCFC) >> 2);
	}
}
