package dev.clientify.client.gui;

import dev.clientify.client.ClientifyClient;
import java.util.Map;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.client.renderer.RenderPipelines;
import net.minecraft.resources.Identifier;

/**
 * The per-module icons shown in the mod list, drawn from one baked atlas of Tabler icons (MIT,
 * https://tabler.io/icons). The atlas is generated by {@code tools/IconAtlas.java}; the whole
 * webfont is not shipped, since twenty-odd glyphs do not justify 2.7 MB.
 *
 * <p>Cell numbers are positions in that atlas and must match the generator's list — add new icons
 * to the END of both, never reorder. A module with no entry falls back to its initial, so nothing
 * breaks by being unlisted.
 */
public final class ModuleIcons {
	public static final Identifier ATLAS = ClientifyClient.id("textures/ui/module_icons.png");
	/** Matches the generator. 48px cells for a ~14px draw: line art survives being shrunk a
	 * little and falls apart when blown up, and a 64px cell was too far from the drawn size. */
	private static final int CELL = 48;
	private static final int COLS = 8;
	private static final int ROWS = 4;

	/** Module id → cell in the atlas. */
	private static final Map<String, Integer> CELLS = Map.ofEntries(
			Map.entry("fps", 0),
			Map.entry("ping", 1),
			Map.entry("reach", 2),
			Map.entry("coords", 3),
			Map.entry("sprint", 4),
			Map.entry("effects", 5),
			Map.entry("armorhud", 6),
			Map.entry("fullbright", 7),
			Map.entry("shulkertooltip", 8),
			Map.entry("hitbox", 9),
			Map.entry("hitcolor", 10),
			Map.entry("saturation", 11),
			Map.entry("customtext", 12),
			Map.entry("itemcounter", 13),
			Map.entry("weather", 14),
			Map.entry("time", 15),
			Map.entry("crosshair", 16),
			Map.entry("zoom", 17),
			Map.entry("nametags", 18),
			Map.entry("title", 19),
			Map.entry("actionbar", 20),
			Map.entry("bossbar", 21),
			Map.entry("scoreboard", 22),
			Map.entry("tab", 23),
			Map.entry("waypoints", 24),
			Map.entry("guiscale", 25),
			Map.entry("attackindicator", 26),
			Map.entry("overlay", 27),
			Map.entry("totem", 28),
			Map.entry("keystrokes", 29));

	private ModuleIcons() {
	}

	public static boolean has(String moduleId) {
		return CELLS.containsKey(moduleId);
	}

	/**
	 * Draws module {@code moduleId}'s icon at {@code size} px, tinted {@code argb}. Returns false
	 * when that module has no icon, leaving the caller to draw whatever it did before.
	 */
	public static boolean draw(GuiGraphics g, String moduleId, int x, int y, int size, int argb) {
		Integer cell = CELLS.get(moduleId);
		if (cell == null) {
			return false;
		}
		int u = (cell % COLS) * CELL;
		int v = (cell / COLS) * CELL;
		g.blit(RenderPipelines.GUI_TEXTURED, ATLAS, x, y, u, v, size, size,
				CELL, CELL, COLS * CELL, ROWS * CELL, argb);
		return true;
	}
}
